// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RCSDolg.Data;

#nullable disable

namespace RCSDolg.Migrations
{
    [DbContext(typeof(BarlangDbContext))]
    [Migration("20251007063317_sqlite.local_migration_656")]
    partial class sqlitelocal_migration_656
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("RCSDolg.Models.Barlang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Hossz")
                        .HasColumnType("REAL");

                    b.Property<double>("Kiterjedes")
                        .HasColumnType("REAL");

                    b.Property<double>("Magassag")
                        .HasColumnType("REAL");

                    b.Property<double>("Melyseg")
                        .HasColumnType("REAL");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telepules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Barlangok");
                });
#pragma warning restore 612, 618
        }
    }
}
